version: "3.7"

services:
  api:
    build: 
      context: ./api
    environment:
      - CONNECTION_STRING=postgres://postgres:postgres@db/postgres_db
    command: node index.js
    volumes:
     - ./api:/api
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      - private
      - public


  web:
    build: 
      context: ./web
    environment:
      - API_URL=http://api:3001/data
    command: node index.js
    volumes:
      - ./web:/web
    depends_on:
      - api
    networks:
      - public
    ports:
      - "80:3000"


  db:
    image: postgres:11.2-alpine
    ports: ["5432"]
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres_db"
    volumes:
      - "db-data:/home/ubuntu/B2Day5/sql_scripts/:/docker-entrypoint-initdb.d"
    networks:
      - private

volumes:
  db-data:

networks:
  public:
  private: